### ISSUE TITLE
Add support for 'dune' rules

### ISSUE THREAD

**Issue by alfa07** [janestreet/jenga-rules#6]
Currently only jbuild rules are supported

**Comment by yminsky** [comment]
This is a little confusing, but jbuild files originated with Jenga, and the original version of Dune was just a simplified, portable  "jbuild interpreter", which was why it was called "jbuilder".

But Dune has evolved since then, and the Jenga jbuild files are not relevant anymore. Indeed, we're internally porting our Jenga rules to run on top of Dune, with the expectation of eliminating the Jenga core in favor of Dune. So I don't think anyone should really be experimenting with Jenga at this point, since it's a dead end at this point.
